sources:
  - url: "https://raw.githubusercontent.com/kubohiroya/ide-gsm-cities-routes/main/cities.csv"
    outputDirectory: "cities-routes"
  - url: "https://raw.githubusercontent.com/kubohiroya/ide-gsm-cities-routes/main/routes.csv"
    outputDirectory: "cities-routes"
  - url: "https://raw.githubusercontent.com/kubohiroya/ide-gsm-countries/main/industries.csv"
    outputDirectory: "countries"
  - url: "https://raw.githubusercontent.com/kubohiroya/ide-gsm-countries/main/countries.csv"
    outputDirectory: "countries"
  - url: "https://raw.githubusercontent.com/kubohiroya/ide-gsm-countries/main/cb.csv"
    outputDirectory: "countries"
  - url: "https://raw.githubusercontent.com/kubohiroya/ide-gsm-countries/main/tariff.csv"
    outputDirectory: "countries"
  - url: "https://raw.githubusercontent.com/kubohiroya/ide-gsm-countries/main/fta.csv"
    outputDirectory: "countries"
  - url: "https://raw.githubusercontent.com/kubohiroya/ide-gsm-countries/main/trade-0.csv"
    outputDirectory: "countries"
  - url: "https://raw.githubusercontent.com/kubohiroya/ide-gsm-countries/main/trade-1.csv"
    outputDirectory: "countries"
  - url: "https://raw.githubusercontent.com/kubohiroya/ide-gsm-countries/main/trade-2.csv"
    outputDirectory: "countries"
  - url: "https://raw.githubusercontent.com/kubohiroya/ide-gsm-countries/main/trade-3.csv"
    outputDirectory: "countries"
  - url: "https://raw.githubusercontent.com/kubohiroya/ide-gsm-countries/main/trade-4.csv"
    outputDirectory: "countries"
  - url: "https://raw.githubusercontent.com/kubohiroya/ide-gsm-countries/main/trade-5.csv"
    outputDirectory: "countries"
  - url: "https://raw.githubusercontent.com/kubohiroya/ide-gsm-countries/main/trade-7.csv"
    outputDirectory: "countries"
  - url: "https://raw.githubusercontent.com/kubohiroya/ide-gsm-ntb/main/nfirm.csv"
    outputDirectory: "ntb"
  - url: "https://raw.githubusercontent.com/kubohiroya/ide-gsm-ntb/main/biNTBMatrix-0.csv"
    outputDirectory: "ntb"
  - url: "https://raw.githubusercontent.com/kubohiroya/ide-gsm-ntb/main/biNTBMatrix-1.csv"
    outputDirectory: "ntb"
  - url: "https://raw.githubusercontent.com/kubohiroya/ide-gsm-ntb/main/biNTBMatrix-2.csv"
    outputDirectory: "ntb"
  - url: "https://raw.githubusercontent.com/kubohiroya/ide-gsm-ntb/main/biNTBMatrix-3.csv"
    outputDirectory: "ntb"
  - url: "https://raw.githubusercontent.com/kubohiroya/ide-gsm-ntb/main/biNTBMatrix-4.csv"
    outputDirectory: "ntb"
  - url: "https://raw.githubusercontent.com/kubohiroya/ide-gsm-ntb/main/biNTBMatrix-5.csv"
    outputDirectory: "ntb"
  - url: "https://raw.githubusercontent.com/kubohiroya/ide-gsm-ntb/main/biNTBMatrix-7.csv"
    outputDirectory: "ntb"
